apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-a2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservice-a2
  template:
    metadata:
      labels:
        app: microservice-a2
    spec:
      containers:
        - name: microservice-a2
          image: pformela/microservice_a_2:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 500Mi
              cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-a2
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: microservice-a2
