version: "3"
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  app:
    container_name: express_app
    build:
      context: ./app
      args:
        - REDIS_HOST=redis
    ports:
      - "3000:3000"
    depends_on:
      - redis
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/messages || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
