services:
  web:
    image: nginx
    networks:
      - my_network
    ports:
      - "80:80"
    environment:
      HOST_DB: db
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  db:
    image: mysql
    networks:
      - my_network
    ports:
      - "3306:3306"
    environment:
      MYSQL_PASSWORD: secret

networks:
  my_network:
    driver: bridge
