version: "3.9"
services:
  db:
    container_name: "db"
    image: mongo:${MONGO_VERSION}
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./mongodb:/data/db
    networks:
      - net_A
  server:
    container_name: "server"
    image: pformela/zadanie2
    restart: always
    ports:
      - "3003:3000"
    networks:
      - net_A
    depends_on:
      - db

networks:
  net_A:
    external: false
    name: net_A
    driver: bridge
