version: "3.9"

services:
  app:
    container_name: app
    image: pformela/lab09zadanie2:latest
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
