version: "3"
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  app:
    container_name: express_app
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - redis
